
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: downloads.datamover.cnsdp.vmware.com
spec:
  group: datamover.cnsdp.vmware.com
  names:
    kind: Download
    listKind: DownloadList
    plural: downloads
    singular: download
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Download describe a velero-plugin restore
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec is the custom resource spec
            properties:
              backupRepositoryName:
                description: BackupRepository provides backup repository info for download. BackupRepositoryName is the name of the BackupRepository.
                type: string
              clonefromSnapshotReference:
                description: CloneFromSnapshotReference is the namespace and clonefromsnapshot name for this download request. The format is CloneFromSnapshotNamespace/CloneFromSnapshotName It is used to update the download status in the clonefromsnapshot.
                type: string
              protectedEntityID:
                description: ProtectedEntityID is the identifier for the protected entity. This is needed to overwrite an existing volume.
                type: string
              restoreTimestamp:
                description: RestoreTimestamp records the time the restore was called. The server's time is used for SnapshotTimestamp
                format: date-time
                type: string
              snapshotID:
                description: SnapshotID is the identifier for the snapshot of the volume.
                type: string
            type: object
          status:
            description: DownloadStatus is the current status of a Download.
            properties:
              completionTimestamp:
                description: CompletionTimestamp records the time an download was completed. Completion time is recorded even on failed downloads. The server's time is used for CompletionTimestamps
                format: date-time
                nullable: true
                type: string
              message:
                description: Message is a message about the download's status.
                type: string
              nextRetryTimestamp:
                description: NextRetryTimestamp should be the timestamp that indicate the next retry for failed download CR. Used to filter out the download request which comes in before next retry time.
                format: date-time
                nullable: true
                type: string
              phase:
                description: Phase is the current state of the Download.
                enum:
                - New
                - InProgress
                - Completed
                - Retry
                - Failed
                type: string
              processingNode:
                description: The DataManager node that has picked up the Download for processing. This will be updated as soon as the Download is picked up for processing. If the DataManager couldn't process Download for some reason it will be picked up by another node.
                type: string
              progress:
                description: Progress holds the total number of bytes of the volume and the current number of restore up bytes. This can be used to display progress information about the restore operation.
                properties:
                  bytesDone:
                    format: int64
                    type: integer
                  totalBytes:
                    format: int64
                    type: integer
                type: object
              retryCount:
                description: RetryCount records the number of retry times for re-adding a failed Download CR which failed due to network issue back to queue. Used for user tracking and debugging.
                format: int32
                type: integer
              startTimestamp:
                description: StartTimestamp records the time an download was started. The server's time is used for StartTimestamps
                format: date-time
                nullable: true
                type: string
              volumeID:
                description: VolumeID is the identifier for the restored volume.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
